export const DEFAULT_ENTRYPOINT_NAMES = ["index", "mod"] as const;
export const DEFAULT_ALLOWED_IMPURE_PUBLIC_SURFACE_PATHS: string[] = [];
export const DEFAULT_ALLOWED_ROOT_FILE_STEMS: string[] = [];
export const DEFAULT_ALLOW_PUBLIC_SURFACE_RE_EXPORT_CHAINS = true;
export const DEFAULT_CENTRAL_SURFACE_PATH_PREFIXES: string[] = [];
export const DEFAULT_DEPENDENCY_POLICIES: {
  mayDependOn: string[];
  name: string;
  pathPrefixes: string[];
}[] = [];
export const DEFAULT_EXPLICIT_PUBLIC_SURFACE_PATHS: string[] = [];

export const DEFAULT_JUNK_DRAWER_DIRECTORY_NAMES: string[] = [];
export const DEFAULT_JUNK_DRAWER_FILE_NAME_PATTERNS: string[] = [];
export const DEFAULT_JUNK_DRAWER_FILE_STEMS: string[] = [];
export const DEFAULT_MAX_DIRECTORY_DEPTH = Number.MAX_SAFE_INTEGER;
export const DEFAULT_MAX_CENTRAL_SURFACE_EXPORTS = Number.MAX_SAFE_INTEGER;
export const DEFAULT_MAX_ENTRYPOINT_RE_EXPORTS = 12;
export const DEFAULT_MAX_INTERNAL_IMPORTS = 12;
export const DEFAULT_MAX_POLICY_FAN_OUT = Number.MAX_SAFE_INTEGER;
export const DEFAULT_MAX_SIBLING_IMPORTS = 7;
export const DEFAULT_MAX_WILDCARD_EXPORTS_PER_PUBLIC_SURFACE =
  Number.MAX_SAFE_INTEGER;
export const DEFAULT_MIN_REPEATED_DEEP_IMPORTS = 3;
export const DEFAULT_REQUIRE_ACYCLIC_DEPENDENCY_POLICIES = false;
export const DEFAULT_REQUIRE_COMPLETE_DEPENDENCY_POLICY_COVERAGE = false;
export const DEFAULT_REQUIRE_TYPE_ONLY_IMPORTS_FOR_TYPE_ONLY_POLICIES = false;
export const DEFAULT_SHARED_HOME_NAMES: string[] = [];
